# Changes here will be overwritten by Copier
SelectCitation:
- AddCitationFile_flag
- AddCFFConvert_flag
SelectCodeQualityFeatures:
- AddLocalTests_flag
- SelectGitHubActions_flag
- AddLinting_flag
- AddPreCommit_flag
- AddEditorConfig_flag
SelectCommunityFeatures:
- AddCodeConduct_flag
- AddContributing_flag
SelectDocumentationFeatures:
- AddLocalDocumentation_flag
- AddOnlineDocumentation_flag
- AddDevDoc_flag
- AddGitHubActionDocumentation_flag
SelectGitHubActions:
- AddGitHubActionBuild_flag
SelectPublishReleaseFeatures:
- SelectCitation_flag
- AddChangeLog_flag
- AddZenodo_flag
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
code_of_conduct_email: nardo.alan@outlook.com
copyright_holder: Cambridge University
email: nardo.alan@outlook.com
full_name: Alan Nardo
github_organization: anardo9
keywords: ''
license: GNUv3
package_name: vbvarsel
package_short_description: Selects variable clusters for experimental design (need
    to fix this later)
template_profile: recommended
version: 0.0.1
